/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Contact/index.vue')['default']
    HTab: typeof import('@headlessui/vue')['Tab']
    HTabGroup: typeof import('@headlessui/vue')['TabGroup']
    HTabList: typeof import('@headlessui/vue')['TabList']
    HTabPanel: typeof import('@headlessui/vue')['TabPanel']
    HTabPanels: typeof import('@headlessui/vue')['TabPanels']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./src/components/Tab/index.vue')['default']
    Tabs: typeof import('./src/components/Tabs/index.vue')['default']
  }
}
