/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('./src/components/AAlert.vue')['default']
    ABadge: typeof import('./src/components/ABadge.vue')['default']
    AButton: typeof import('./src/components/AButton.vue')['default']
    ACard: typeof import('./src/components/ACard.vue')['default']
    AContact: typeof import('./src/components/AContact/index.vue')['default']
    AContactDetails: typeof import('./src/components/AContact/AContactDetails.vue')['default']
    ADescription: typeof import('./src/components/ADescription.vue')['default']
    AFormItem: typeof import('./src/components/AFormItem.vue')['default']
    AStatistic: typeof import('./src/components/AStatistic.vue')['default']
    ATab: typeof import('./src/components/ATab/index.vue')['default']
    HTab: typeof import('@headlessui/vue')['Tab']
    HTabGroup: typeof import('@headlessui/vue')['TabGroup']
    HTabList: typeof import('@headlessui/vue')['TabList']
    HTabPanel: typeof import('@headlessui/vue')['TabPanel']
    HTabPanels: typeof import('@headlessui/vue')['TabPanels']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
